services:
  db:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: eo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
